### ISSUE TITLE
This line in your styles.css somehow worked its way into the reading mode of code display, and makes the text bold 

### ISSUE THREAD

**Issue by stanley-910** [tabibyte/obsifetch#5]
Reading mode with Obsifetch On: 
<img width="689" alt="image" src="https://github.com/user-attachments/assets/776038ec-8743-48a9-ae7a-0d74924413a3">

with Obsifetch Off: 
<img width="577" alt="image" src="https://github.com/user-attachments/assets/632aef68-5885-4e66-abbc-d78507c1323f">

This line is the culprit: 

```css
pre {
    margin: 0;
    white-space: pre;
    color: var(--text-accent);
    /*font-weight: bold;*/
    line-height: 1.1;
}
```

The commented out line in particular. Not sure how it it started affecting my actual files, as it wasn't bolded after I first installed.  I also haven't taken a look at your TypeScript, so maybe its a weird me thing
